table Data
	lineageTag: 34b53f52-32cc-4c93-8076-499cedccee73

	column Category
		dataType: string
		lineageTag: 02caed15-d0ba-4255-b716-cd9ae1c4cb74
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Price
		dataType: int64
		formatString: 0
		lineageTag: 9898f16d-d2fa-4a73-bd1d-f83a9b4d94bf
		summarizeBy: sum
		sourceColumn: Price

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 48bb7a66-f30c-48f9-9b06-7c4a925f2b38
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	partition Data = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WcsrMTlXSUQrSNTQFUiYGQMJIKVYnWsk5J78kA8jzSk3MKwaJgqRMwVLBBflFJSAx56LM5OzUEiDLECRrohQbCwA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Category = _t, Subcategory = _t, Price = _t, Quantity = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Category", type text}, {"Subcategory", type text}, {"Price", Int64.Type}, {"Quantity", Int64.Type}}),
				    #"Columns removed by Measure Killer"= Table.SelectColumns(#"Changed Type",{"Category","Quantity","Price"})
				in
				    #"Columns removed by Measure Killer"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

