table 'New Measure'
	lineageTag: 765e2915-197b-47e9-8dda-49dfd622cd1d

	measure 'Total Sales' =
			
			SUMX(
			    'Data',
			    'Data'[Price] * 'Data'[Quantity]
			)
		formatString: 0
		lineageTag: 82986e4c-347a-4f4d-b48c-f0c32a8cc0d5

	measure Heading = " Sales Report as on " & FORMAT(TODAY(), "dd-mmm-yy")
		lineageTag: f4ae893a-0efa-43e9-b73c-bbff68af3aed

	measure 'Sports Sale' =
			
			CALCULATE(
			    [Total Sales],
			    'Data'[Category] = "Sports"
			)
		formatString: 0
		lineageTag: 3349e028-868d-4246-80d4-5b3ef107b466

	partition 'New Measure' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

